version: '3.9'

services:
  postgres:
    image: postgres
    container_name: vkr-muiv-postgres
    restart: always
    networks:
      - mynetwork
    ports:
    - 5432:5432
    volumes:
      - postgres:/data/db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGDATA: /data/db

  java:
    image: tripp/muiv-vkr:v1
    container_name: vkr-muiv-java
    restart: always
    platform: linux/amd64
    networks:
      - mynetwork
    ports:
      - 8080:8080


volumes:
  pgdata:
  postgres:
  pgadmin:

networks:
  mynetwork:
    driver: bridge
